{% set version = "4.6.0" %}

package:
  name: python-socketio
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/p/python-socketio/python-socketio-{{ version }}.tar.gz
  sha256: 358d8fbbc029c4538ea25bcaa283e47f375be0017fcba829de8a3a731c9df25a

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python
    - pip
  run:
    - python
    - six >=1.9.0
    - python-engineio >=3.9.0

test:
  requires:
    - pip
  commands:
    - pip check
  imports:
    - socketio
    - socketio.base_manager
    - socketio.kombu_manager
    - socketio.middleware
    - socketio.namespace
    - socketio.packet
    - socketio.pubsub_manager
    - socketio.redis_manager
    - socketio.server

about:
  home: https://github.com/miguelgrinberg/python-socketio/
  license_file: LICENSE
  license: MIT
  license_family: MIT
  summary: Socket.IO server
  doc_url: https://python-socketio.readthedocs.io/
  dev_url: https://github.com/miguelgrinberg/python-socketio/


extra:
  recipe-maintainers:
    - pmlandwehr
    - ReimarBauer
