{% set version = "5.11.2" %}

package:
  name: python-socketio
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/p/python-socketio/python-socketio-{{ version }}.tar.gz
  sha256: ae6a1de5c5209ca859dc574dccc8931c4be17ee003e74ce3b8d1306162bb4a37

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - python >=3.8
    - bidict >=0.21.0
    - python-engineio >=4.8.0

test:
  requires:
    - pip
  commands:
    - pip check
  imports:
    - socketio
    - socketio.base_manager
    - socketio.kombu_manager
    - socketio.middleware
    - socketio.namespace
    - socketio.packet
    - socketio.pubsub_manager
    - socketio.redis_manager
    - socketio.server

about:
  home: https://github.com/miguelgrinberg/python-socketio/
  license_file: LICENSE
  license: MIT
  license_family: MIT
  summary: Socket.IO server
  doc_url: https://python-socketio.readthedocs.io/
  dev_url: https://github.com/miguelgrinberg/python-socketio/


extra:
  recipe-maintainers:
    - ReimarBauer
    - synapticarbors
