travis:
  secure:
    BINSTAR_TOKEN: jvvOhtIebxlsl+OdHsLAwZAVxoKo1jlUFIBkIMHdZb47/noNYi/fEFytvaVmVnYE6YsqbFmL0DA/hYVNj4Qz7Y9KzAEQn3S6WUeSLPf8JfL2Ko8vok8hh0qEVOgf+t/t/Z+d2mX0SMDjcKwlO0KwQQWMI1dXXtccg/PSMoU3VYDVCHk/F3I48qQAi7mhiwebrxP5z22SQsgxa6mQmDVDFrUDSzmMemWLUwOg+QqUjrGeKFClbjz138Ju7jShCGx/7gH604k1ND97p1gtAyEBq7bwJhRBEPgSNxA4aHm6pq21lo+H0OxGqbp+m+qhPtqH/1EGa5bBHkqyNtuSwex8QPPXDj+C5AMs7Fe6gcLT8yhyq7wDpEyUQYdA11aF8fnGKohZob4pw56reJE4xSWSrCPy7D7t59wj3Z4q513enKQC4/JjqBmKObRu8tXVTWptw0M+dhZwS6Rl4UYNPAQQGaWLhcWHyNEJXtmwRc1ptsTTfieqOKuq7Tq+9it0IfhP/BpXqsLWCWa9rebWQYTOrhxzWI+M7lzjteYZdN0ACSNoCgHwhos9W5Gz8MrrECowEZO69fN02KRT9UW5zyzzqDHO0pxBuijperpP/bLtrwZJQjn6M/nF2eMko1SND+utvSBbnAshH/lHRlRznrWquPRGpZzm6fjr4agCX2An46c=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
